//! MeshCore vanity Ed25519 key generator.
//!
//! Absorbed from https://github.com/samschlegel/mc-keygen (upstream commit
//! 62ed67f), dual-licensed MIT or Apache-2.0. See ATTRIBUTION.md for what was
//! kept and what was removed.
//!
//! This binary is driven by the Python harvester, so it favours being scripted
//! over being watched: the result goes to stdout, progress goes to stderr as
//! plain text, and every failure path returns through one place.

// Upstream declared these modules again here, which compiled every source file
// twice — once into the library, once into the binary. Using the library is
// the same code and half the build.
#[cfg(feature = "cuda")]
use mc_keygen::gpu;
use mc_keygen::{keygen, search, types};

use std::io::{self, BufRead, Write};
use std::process::ExitCode;
use std::time::{Duration, Instant};

use clap::{Parser, Subcommand};
use serde::{Deserialize, Serialize};

use search::SearchHandle;

/// How often the plain-text progress line is refreshed.
const PROGRESS_INTERVAL: Duration = Duration::from_millis(500);

#[derive(Parser)]
#[command(
    name = "mc-keygen",
    version,
    about = "MeshCore vanity Ed25519 key generator",
    args_conflicts_with_subcommands = true,
    subcommand_negates_reqs = true
)]
struct Cli {
    #[command(subcommand)]
    command: Option<Command>,

    /// Hex prefix(es) to search for (1-62 chars, 0-9/A-F each)
    #[arg(required = true)]
    prefix: Vec<String>,

    /// Number of worker threads (default: all cores)
    #[arg(short = 't', long = "threads")]
    threads: Option<usize>,

    /// Output the result as JSON on stdout
    #[arg(long)]
    json: bool,

    /// Force CPU-only search (no GPU even if available)
    #[cfg(feature = "gpu")]
    #[arg(long, conflicts_with = "gpu_only")]
    cpu_only: bool,

    /// Force GPU-only search (no CPU threads)
    #[cfg(feature = "gpu")]
    #[arg(long, conflicts_with = "cpu_only")]
    gpu_only: bool,

    /// Cross-check GPU key generation against the host implementation and exit
    #[cfg(feature = "gpu")]
    #[arg(long)]
    verify: bool,
}

#[derive(Subcommand)]
enum Command {
    /// Stream prefix-pattern matches and exact statistics as JSON Lines (policy-v2).
    Harvest {
        /// Screening policy generated by meshcore_vanity.harvest
        #[arg(long)]
        policy: std::path::PathBuf,
        /// Search duration after initialization (seconds)
        #[arg(long, default_value_t = 900.0)]
        seconds: f64,
        /// Native CPU worker count
        #[arg(long, default_value_t = 1)]
        threads: usize,
        /// Stop gracefully on a line or EOF from stdin (supervisor protocol)
        #[arg(long)]
        stdin_stop: bool,
        /// Emit statistics only; discard matches without printing private keys
        #[arg(long)]
        benchmark: bool,
        /// Require CUDA harvesting; never silently fall back to CPU
        #[cfg(feature = "cuda")]
        #[arg(long)]
        gpu_only: bool,
    },
    /// Verify saved public/private key pairs, reading JSON Lines on stdin.
    ///
    /// Each line is an object with `public_key` and `private_key` as hex; one
    /// verdict object per line is written to stdout.
    ///
    /// This exists because keys found on the GPU have no seed to re-derive
    /// from, so the harvester would otherwise have to do Ed25519 scalar
    /// multiplication in Python — about 95 ms per key, against microseconds
    /// here.
    VerifyPairs,
}

// --- Errors ---------------------------------------------------------------

/// Everything that can go wrong, so `main` has a single exit point.
#[derive(Debug)]
enum Failure {
    Usage(String),
    NoGpu,
    Search(String),
    #[cfg(feature = "cuda")]
    Verification(String),
    Io(io::Error),
}

impl std::fmt::Display for Failure {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Failure::Usage(message) => write!(f, "{}", message),
            Failure::NoGpu => write!(f, "--gpu-only was requested but no GPU is available"),
            Failure::Search(message) => write!(f, "{}", message),
            #[cfg(feature = "cuda")]
            Failure::Verification(message) => write!(f, "GPU verification failed: {}", message),
            Failure::Io(error) => write!(f, "{}", error),
        }
    }
}

impl From<io::Error> for Failure {
    fn from(error: io::Error) -> Self {
        Failure::Io(error)
    }
}

// --- Prefix validation ----------------------------------------------------

pub(crate) fn validate_prefix(prefix: &str) -> Result<String, String> {
    let upper = prefix.to_ascii_uppercase();

    // Cap is 62 not 64: nibble 63 lands on the high nibble of pubkey[31], which
    // contains the Ed25519 sign bit. The GPU kernel's fast path skips writing
    // that bit (saves an fe_mul per iteration), so a prefix that reads byte 31
    // would compare against a zeroed sign bit and miss real matches.
    if upper.is_empty() || upper.len() > 62 {
        return Err(format!(
            "prefix must be 1-62 hex characters, got {} characters",
            upper.len()
        ));
    }

    if !upper.bytes().all(|c| c.is_ascii_hexdigit()) {
        return Err(format!("prefix must be valid hex (0-9, A-F), got '{}'", prefix));
    }

    // Reject prefixes that would always start with 00 or FF.
    if upper.starts_with("00") || upper.starts_with("FF") {
        return Err(format!(
            "prefix '{}' starts with 00 or FF, which are skipped by MeshCore",
            upper
        ));
    }

    Ok(upper)
}

// --- Formatting -----------------------------------------------------------

fn format_number(n: u64) -> String {
    let s = n.to_string();
    let mut result = String::new();
    for (i, c) in s.chars().rev().enumerate() {
        if i > 0 && i % 3 == 0 {
            result.push(',');
        }
        result.push(c);
    }
    result.chars().rev().collect()
}

fn format_duration(secs: f64) -> String {
    if secs < 60.0 {
        format!("{:.1}s", secs)
    } else if secs < 3600.0 {
        let mins = (secs / 60.0).floor();
        format!("{}m {:.0}s", mins as u64, secs - mins * 60.0)
    } else {
        let hours = (secs / 3600.0).floor();
        let rem = secs - hours * 3600.0;
        format!("{}h {}m", hours as u64, (rem / 60.0).floor() as u64)
    }
}

// --- Batch verification ---------------------------------------------------

#[derive(Deserialize)]
struct PairRequest {
    public_key: String,
    private_key: String,
}

#[derive(Serialize)]
struct PairVerdict {
    public_key: String,
    /// True when the private key really does derive this public key.
    valid: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    error: Option<String>,
}

fn verify_pairs() -> Result<(), Failure> {
    let stdin = io::stdin();
    let stdout = io::stdout();
    let mut out = stdout.lock();

    for line in stdin.lock().lines() {
        let line = line?;
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        let verdict = match serde_json::from_str::<PairRequest>(trimmed) {
            Ok(request) => match keygen::public_key_from_private_hex(&request.private_key) {
                Ok(derived) => PairVerdict {
                    valid: derived.eq_ignore_ascii_case(&request.public_key),
                    public_key: request.public_key,
                    error: None,
                },
                Err(message) => PairVerdict {
                    public_key: request.public_key,
                    valid: false,
                    error: Some(message),
                },
            },
            Err(error) => PairVerdict {
                public_key: String::new(),
                valid: false,
                error: Some(format!("malformed request: {}", error)),
            },
        };
        writeln!(out, "{}", serde_json::to_string(&verdict).expect("verdict serialises"))?;
    }
    out.flush()?;
    Ok(())
}

// --- GPU discovery --------------------------------------------------------

#[allow(unused_variables)]
pub(crate) fn try_init_gpu(prefixes: &[String]) -> Vec<Box<dyn search::GpuSearcher>> {
    #[cfg(feature = "cuda")]
    {
        match gpu::CudaSearcher::new(prefixes) {
            Ok(searcher) => return vec![Box::new(searcher)],
            Err(error) => {
                eprintln!("Warning: CUDA GPU unavailable ({}), using CPU only", error);
                return vec![];
            }
        }
    }
    #[cfg(not(feature = "gpu"))]
    {
        vec![]
    }
}

fn gpu_names_label(searchers: &[Box<dyn search::GpuSearcher>]) -> String {
    searchers
        .iter()
        .map(|g| g.device_name())
        .collect::<Vec<_>>()
        .join(", ")
}

// --- Search ---------------------------------------------------------------

/// Follow a running search, reporting progress on stderr so stdout stays clean.
fn await_result(
    handle: SearchHandle,
    expected: u64,
    mode_label: &str,
    quiet: bool,
) -> Result<types::SearchResult, Failure> {
    if !quiet {
        eprintln!("Searching ({})...", mode_label);
    }
    let mut last_report = Instant::now();
    while !handle.is_done() {
        std::thread::sleep(Duration::from_millis(50));
        if quiet || last_report.elapsed() < PROGRESS_INTERVAL {
            continue;
        }
        last_report = Instant::now();
        let stats = handle.stats(expected);
        eprint!(
            "\r  {} keys | {} | {} keys/sec | {:.0}% of expected     ",
            format_number(stats.attempts),
            format_duration(stats.elapsed_secs),
            format_number(stats.keys_per_sec as u64),
            100.0 * stats.attempts as f64 / stats.expected_attempts.max(1) as f64,
        );
        let _ = io::stderr().flush();
    }
    if !quiet {
        eprintln!();
    }
    handle.finish().map_err(|e| Failure::Search(e.to_string()))
}

fn run_search(cli: &Cli) -> Result<(), Failure> {
    let mut prefixes = Vec::with_capacity(cli.prefix.len());
    for raw in &cli.prefix {
        prefixes.push(validate_prefix(raw).map_err(Failure::Usage)?);
    }

    #[cfg(feature = "cuda")]
    if cli.verify {
        eprint!("Compiling the GPU kernel and cross-checking against the host... ");
        return match gpu::verify_gpu_keygen() {
            Ok(()) => {
                eprintln!("passed");
                Ok(())
            }
            Err(error) => Err(Failure::Verification(error.to_string())),
        };
    }

    // Expected attempts: shortest prefix, divided by how many share that length.
    let min_len = prefixes.iter().map(|p| p.len()).min().expect("at least one prefix");
    let same_len = prefixes.iter().filter(|p| p.len() == min_len).count() as u64;
    let expected = 16u64.saturating_pow(min_len as u32) / same_len.max(1);

    let prefix_label = if prefixes.len() == 1 {
        String::new()
    } else {
        format!(", {} prefixes", prefixes.len())
    };

    #[cfg(feature = "gpu")]
    let (cpu_only, gpu_only) = (cli.cpu_only, cli.gpu_only);
    #[cfg(not(feature = "gpu"))]
    let (cpu_only, gpu_only) = (true, false);

    let gpu_searchers = if cpu_only { vec![] } else { try_init_gpu(&prefixes) };

    // Hybrid mode reserves cores for the GPU dispatch thread; pure CPU uses all
    // logical cores. An explicit -t overrides either default.
    let num_threads = cli.threads.unwrap_or_else(|| {
        if !gpu_searchers.is_empty() && !gpu_only {
            search::default_hybrid_cpu_threads(gpu_searchers.len())
        } else {
            std::thread::available_parallelism().map(|n| n.get()).unwrap_or(1)
        }
    });

    let (handle, mode_label) = if gpu_only {
        if gpu_searchers.is_empty() {
            return Err(Failure::NoGpu);
        }
        let label = format!("{}{}", gpu_names_label(&gpu_searchers), prefix_label);
        (SearchHandle::start_gpu(&prefixes, gpu_searchers), label)
    } else if gpu_searchers.is_empty() {
        let label = format!("{} threads{}", num_threads, prefix_label);
        (SearchHandle::start(&prefixes, num_threads), label)
    } else {
        let label = format!(
            "{} + {} threads{}",
            gpu_names_label(&gpu_searchers),
            num_threads,
            prefix_label
        );
        (
            SearchHandle::start_hybrid(&prefixes, num_threads, gpu_searchers),
            label,
        )
    };

    let result = await_result(handle, expected, &mode_label, cli.json)?;

    if cli.json {
        println!("{}", serde_json::to_string(&result).expect("result serialises"));
    } else {
        eprintln!(
            "Found after {} attempts in {} ({} keys/sec)",
            format_number(result.attempts),
            format_duration(result.elapsed_secs),
            format_number((result.attempts as f64 / result.elapsed_secs.max(1e-9)) as u64),
        );
        println!("public_key  {}", result.public_key);
        println!("private_key {}", result.private_key);
        println!("matched     {}", result.matched_prefix);
    }
    Ok(())
}

// --- Entry point ----------------------------------------------------------

fn main() -> ExitCode {
    let cli = Cli::parse();

    let outcome = match &cli.command {
        Some(Command::VerifyPairs) => verify_pairs(),
        Some(Command::Harvest { policy, seconds, threads, stdin_stop, benchmark,
            #[cfg(feature = "cuda")] gpu_only,
        }) => run_harvest(policy, *seconds, *threads, *stdin_stop, *benchmark,
            { #[cfg(feature = "cuda")] { *gpu_only }
              #[cfg(not(feature = "cuda"))] { false } }),
        None => run_search(&cli),
    };

    match outcome {
        Ok(()) => ExitCode::SUCCESS,
        Err(failure) => {
            eprintln!("error: {}", failure);
            ExitCode::FAILURE
        }
    }
}

fn run_harvest(path: &std::path::Path, seconds: f64, threads: usize,
               stdin_stop: bool, benchmark: bool, gpu_only: bool) -> Result<(), Failure> {
    use std::sync::{Arc, atomic::{AtomicBool, Ordering}};
    use mc_keygen::harvest::HarvestPolicy;
    if !seconds.is_finite() || seconds <= 0.0 || seconds > 86400.0 || !(1..=1024).contains(&threads) {
        return Err(Failure::Usage("harvest seconds must be in (0, 86400] and threads in 1..1024".into()));
    }
    let file = std::fs::File::open(path)?;
    if file.metadata()?.len() > 8 * 1024 * 1024 {
        return Err(Failure::Usage("harvest policy is too large".into()));
    }
    let policy: HarvestPolicy = serde_json::from_reader(file).map_err(|_| Failure::Usage("invalid harvest policy JSON".into()))?;
    policy.validate().map_err(Failure::Usage)?;
    let stop = Arc::new(AtomicBool::new(false));
    if stdin_stop {
        let control = Arc::clone(&stop);
        std::thread::spawn(move || {
            let mut line = String::new();
            let _ = io::stdin().read_line(&mut line);
            control.store(true, Ordering::Relaxed);
        });
    }
    if gpu_only {
        #[cfg(feature = "cuda")]
        return mc_keygen::gpu_harvest::run_gpu(policy, seconds, stop, benchmark).map_err(Failure::Search);
        #[cfg(not(feature = "cuda"))]
        return Err(Failure::NoGpu);
    }
    mc_keygen::harvest::run_cpu(policy, threads, seconds, stop, benchmark).map_err(Failure::Search)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prefixes_are_upper_cased() {
        assert_eq!(validate_prefix("c0ffee").unwrap(), "C0FFEE");
    }

    #[test]
    fn reserved_prefixes_are_rejected() {
        assert!(validate_prefix("00AB").is_err());
        assert!(validate_prefix("ffAB").is_err());
    }

    #[test]
    fn non_hex_is_rejected() {
        assert!(validate_prefix("COFFEE").is_err(), "the letter O is not hex");
        assert!(validate_prefix("").is_err());
        assert!(validate_prefix(&"A".repeat(63)).is_err());
    }

    #[test]
    fn the_longest_usable_prefix_is_accepted() {
        assert_eq!(validate_prefix(&"A".repeat(62)).unwrap().len(), 62);
    }

    #[test]
    fn numbers_are_grouped() {
        assert_eq!(format_number(1_234_567), "1,234,567");
        assert_eq!(format_number(0), "0");
    }

    #[test]
    fn durations_read_naturally() {
        assert_eq!(format_duration(45.0), "45.0s");
        assert_eq!(format_duration(90.0), "1m 30s");
        assert_eq!(format_duration(7200.0), "2h 0m");
    }
}
